### ISSUE TITLE
Ivalid WPS information elemnt id

### ISSUE THREAD

**Issue by 5rzmz8odb** [6e726d/wig-ng#5]
Hi @6e726d any idea on how to solve this error?

![image](https://user-images.githubusercontent.com/64424135/160306590-dfb702cf-5a0c-4d9d-a292-c23977aa0d33.png)

Looking for audit p2p wifi-direct peers

**Comment by 6e726d** [comment]
Hi @desegura this project doesn't have support for python3 yet. Did you make any modification to make it work?

**Comment by desegura** [comment]
Hi thought python3 branch does. I did any modification to the code.
I'm running on kali 2021.2 with a TL-WN722N

**Comment by desegura** [comment]
I make it run finally, is a good tool!
BTW in your Wi-Fi Direct To Hell presentation, when you talk about mac cloning, which is the wpa_cli command to avoid pbc or PIN input? because p2p_connect <mac> always asks for the PIN 🤔

thanks!

**Comment by 6e726d** [comment]
I removed the python3 branch and started working on a major refactoring to make it work with Python 3.
Are you running the tool with Python 2?
Regarding the Wi-Fi  Direct question, please send me an email to avoid using the issues for questions that are not related to the tool.

**Comment by desegura** [comment]
Cool. Yes I got it working yesterday with python 2.7.1 in a virtualenv
Thanks for helping!

**Comment by 6e726d** [comment]
Closing this issue due to the fact that it's related to bugs on the python3 branch. Python 3 support is being work on.
